# Generated by Django 3.0.3 on 2020-03-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Единицы измерения')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'db_table': 'measurement',
            },
        ),
    ]
