# Generated by Django 3.0.3 on 2020-03-10 14:03
from django.core.management import call_command
from django.db import migrations

AGE_MODEL_NAME = 'Age'
APP_LABEL = 'medical_test'
FIXTURE_NAME = 'age.json'
LOAD_DATA_COMMAND = 'loaddata'


def load_ages_from_fixture(apps, schema_editor):
    call_command(LOAD_DATA_COMMAND, FIXTURE_NAME)


def delete_ages(apps, schema_editor):
    Age = apps.get_model(APP_LABEL, AGE_MODEL_NAME)
    Age.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('medical_test', '0002_age_medicalprocedure_medicalprocedureresult_parameter_parametervalue'),
    ]

    operations = [
        migrations.RunPython(load_ages_from_fixture, delete_ages)
    ]
