# Generated by Django 3.0.3 on 2020-03-10 14:41
from django.core.management import call_command
from django.db import migrations

MEASUREMENT_MODEL_NAME = 'Measurement'
APP_LABEL = 'medical_test'
FIXTURE_NAME = 'measurement.json'
LOAD_DATA_COMMAND = 'loaddata'


def load_measurements_from_fixture(apps, schema_editor):
    call_command(LOAD_DATA_COMMAND, FIXTURE_NAME)


def delete_measurements(apps, schema_editor):
    Measurement = apps.get_model(APP_LABEL, MEASUREMENT_MODEL_NAME)
    Measurement.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('medical_test', '0003_auto_20200310_1403'),
    ]

    operations = [
        migrations.RunPython(load_measurements_from_fixture, delete_measurements)
    ]
