# Generated by Django 3.0.3 on 2020-03-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_test', '0004_auto_20200310_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='maximum_border',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='minimum_border',
        ),
        migrations.AddField(
            model_name='parameter',
            name='female_maximum_border',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Верхняя граница женщины'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='female_minimum_border',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Нижняя граница женщины'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='male_maximum_border',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Врехняя граница мужчины'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='male_minimum_border',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Нижняя граница мужчины'),
        ),
    ]
