# Generated by Django 3.0.3 on 2020-03-13 09:20

from django.core.management import call_command
from django.db import migrations

CARDIOVASCULAR_SCORE_MODEL_NAME = 'CardiovascularScore'
APP_LABEL = 'medical_test'
FIXTURE_NAME = 'cardiovascular_score.json'
LOAD_DATA_COMMAND = 'loaddata'


def load_score_from_fixture(apps, schema_editor):
    call_command(LOAD_DATA_COMMAND, FIXTURE_NAME)


def delete_score(apps, schema_editor):
    CardiovascularScore = apps.get_model(APP_LABEL,
                                         CARDIOVASCULAR_SCORE_MODEL_NAME)
    CardiovascularScore.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('medical_test', '0008_auto_20200313_0919'),
    ]

    operations = [
        migrations.RunPython(load_score_from_fixture, delete_score)
    ]
